install: ./travis.sh install
script: ./travis.sh script
env:
  - UPB_TRAVIS_BUILD=bare
  - UPB_TRAVIS_BUILD=barejit
  - UPB_TRAVIS_BUILD=core32
  - UPB_TRAVIS_BUILD=withprotobuf
  - UPB_TRAVIS_BUILD=lua
